{"name": "test_loginsalesforce_validcredentials[test_list_item0]", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'authenticate_salesforce'", "trace": "self = <testcases.login_test.TestLogin object at 0x000001F0D8A6D950>, test_list_item = {'password': 'Pra245pte#', 'username': 'pgbitbucket706@agentforce.com'}\n\n    @pytest.mark.flaky(reruns=2)\n    @pytest.mark.smoke\n    @pytest.mark.parametrize(\"test_list_item\", BaseTest.get_data_from_json(Login_test_data_path,\"valid_login\"))\n    def test_loginsalesforce_validcredentials(self,test_list_item):\n        #loginpage = LoginPage(self.driver)\n        #homepage = loginpage.logintosalesforce(test_list_item[\"username\"],test_list_item[\"password\"])\n        #homepage.verify_page_title()\n>       self.authenticate_salesforce()\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       AttributeError: 'TestLogin' object has no attribute 'authenticate_salesforce'\n\ntestcases\\login_test.py:20: AttributeError"}, "parameters": [{"name": "test_list_item", "value": "{'username': 'pgbitbucket706@agentforce.com', 'password': 'Pra245pte#'}"}], "start": 1750167631345, "stop": 1750167631345, "uuid": "cfe6a85f-ac7b-4597-a70f-61891979662b", "historyId": "4fa26c5d8a8f3f216283ca707f04bde8", "testCaseId": "edd327156eda62a83bae9df650959eeb", "fullName": "testcases.login_test.TestLogin#test_loginsalesforce_validcredentials", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-QPHGE425"}, {"name": "thread", "value": "23440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.login_test"}]}