{"uuid": "36eae622-263f-44e5-9c70-9756b0124445", "children": ["22dbe2a1-4af4-4bc7-8594-ac23b1cbc58f"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1750010631290, "stop": 1750010631290}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: chrome=137.0.7151.104)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff606fbfe75+79173]\n\tGetHandleVerifier [0x0x7ff606fbfed0+79264]\n\t(No symbol) [0x0x7ff606d79e5a]\n\t(No symbol) [0x0x7ff606d65c25]\n\t(No symbol) [0x0x7ff606d8ac44]\n\t(No symbol) [0x0x7ff606e003c5]\n\t(No symbol) [0x0x7ff606e20922]\n\t(No symbol) [0x0x7ff606df8743]\n\t(No symbol) [0x0x7ff606dc14c1]\n\t(No symbol) [0x0x7ff606dc2253]\n\tGetHandleVerifier [0x0x7ff60728a2ad+3004797]\n\tGetHandleVerifier [0x0x7ff6072846fd+2981325]\n\tGetHandleVerifier [0x0x7ff6072a3350+3107360]\n\tGetHandleVerifier [0x0x7ff606fda9fe+188622]\n\tGetHandleVerifier [0x0x7ff606fe228f+219487]\n\tGetHandleVerifier [0x0x7ff606fc8dc4+115860]\n\tGetHandleVerifier [0x0x7ff606fc8f79+116297]\n\tGetHandleVerifier [0x0x7ff606faf528+11256]\n\tBaseThreadInitThunk [0x0x7ffcdfade8d7+23]\n\tRtlUserThreadStart [0x0x7ffce1c1c34c+44]\n\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"D:\\Udmey\\Python-Workspace\\SalesforceAutomationPoc\\testcases\\conftest.py\", line 53, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"failed_test\",\n                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1019, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1029, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750010721220, "stop": 1750010721242}], "start": 1750010631290, "stop": 1750010721242}